import type { Metadata } from "next";
import "./globals.css";
import { Glass_Antiqua } from "next/font/google";
import { DevTools } from "./Devtools";

// import Provider from "@/app/_trpc/Provider";
// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const glassAntiqua = Glass_Antiqua({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${glassAntiqua.className} h-screen w-screen`}>
        {/* <Provider> */}
        <DevTools />
        {children}
        {/* <ReactQueryDevtools /> */}
        {/* </Provider> */}
      </body>
    </html>
  );
}
